#!/usr/bin/ruby
############################################################################
#
# Project Euler - Problem 002
#
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# 
# Answer: 4613732
############################################################################

v1 = 1
v2 = 2
v3 = 0
sum = 0
max = 4000000

while v2 < max
    if v2 % 2 == 0
        sum = sum + v2
    end
    v3 = v2 + v1
    v1 = v2
    v2 = v3
end
print "Total is: #{sum}\n"