=begin

The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

=end

$max_divisors = 500

$count = 1
$triangle = 1

$max = 0

def divisors(x)
    i = 1
    c = 1
    while (i * i <= x)
        if x%i == 0
            c += 2
            end
        i += 1
        end
    if c > $max
        $max = c
        end
        return c
    end


while (divisors($triangle) <= $max_divisors)
    $count += 1
    $triangle += $count
    end

div = divisors($triangle)
print "Answer is #{$triangle} which has #{div} divisors.\n"
